# docker-compose.yml
version: '3'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ERROR_RATE=0.2
      - TIMEOUT_SECONDS=2.0
    volumes:
      - ./app:/app
    restart: always
